server:
  port: 8080
  session:
    # 设置session过期时间，单位是秒，默认30分钟，最少1分支
    timeout: 600

spring:
  thymeleaf:
    cache: false
    encoding: UTF-8
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    http://database.51cto.com/art/201005/199278.htm
    url: jdbc:mysql://192.168.33.10:3306/jiiiiiin-security-demo?&useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 1qaz@WSX
  # 配置redis链接地址
  redis:
    host: 127.0.0.1
    port: 6379
  session:
    store-type: redis


#security:
#  basic:
#    enabled: false

thymeleaf:
  cache: false


swagger:
  enable: true

# 自定义配置
jiiiiiin:
  security:
    validate:
      image-code:
        length: 3
        size: 30
        interceptor-urls: /user/*,/admin/*
    social:
      # 拦截auth2授权地址
      # TODO 需要根据配置在qq开发者平台中的接口地址匹配，最好还原成默认的social SocialAuthenticationFilter 中的/auth
      filter-processes-url: /qqLogin
      qq:
        # 配置qq auth服务器回调处理接口
        # TODO 需要根据配置在qq开发者平台中的接口地址匹配，最好换成/qq
        provider-id: callback.do
        app-id: 100550231
        app-secret: 69b6ab57b22f3c2fe6a6149274e3295e
      ##微信登录配置，参见WeixinProperties
      weixin:
        # 配置 weixin auth服务器回调处理接口
        app-id: wxd99431bbff8305a0
        app-secret: 60f78681d063590a469f1b297feff3c4
    browser:
      sign-up-url: /demo-signUp.html
      sign-out-url: /demo-signOut.html
#      signInUrl: /demo-signIn.html


