spring:
  thymeleaf:
    cache: false
    encoding: UTF-8
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    http://database.51cto.com/art/201005/199278.htm
    url: jdbc:mysql://127.0.0.1:3306/jiiiiiin-security-demo?&useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: root
  session:
    store-type: none

#security:
#  basic:
#    enabled: false


swagger:
  enable: true

# 自定义配置
jiiiiiin:
  security:
    validate:
      image-code:
        length: 3
        size: 30
        interceptor-urls: /user/*
    social:
      qq:
        app-id: 100550231
        app-secret: 69b6ab57b22f3c2fe6a6149274e3295e

#        jiiiiiin.security.social.qq", name = "app-id
#    browser:
#      loginPage: /demo-signIn.html

