server:
  context-path: /order

# 单节点配置
spring:
  profiles:
    active: node1
  application:
    name: jiiiiiin-order
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      # 指定服务注册中心的地址
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

---
# 多节点配置
# 运行时本地可以通过指定：`-Dspring.profiles.active=node2`方式启动多个服务节点

spring:
  profiles: node1
server:
  port: 8000

---

spring:
  profiles: node2
server:
  port: 8001

