server:
  port: 8080

spring:
  thymeleaf:
    cache: false
    encoding: UTF-8
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    http://database.51cto.com/art/201005/199278.htm
    url: jdbc:mysql://127.0.0.1:3306/jiiiiiin-security-demo?&useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: root
  session:
    store-type: none

#security:
#  basic:
#    enabled: false


swagger:
  enable: true

# 自定义配置
jiiiiiin:
  security:
    validate:
      image-code:
        length: 3
        size: 30
        interceptor-urls: /user/*
    social:
      # 拦截auth2授权地址
      filter-processes-url: /qqLogin
      qq:
        # 配置qq auth服务器回调处理接口
        provider-id: callback.do
        app-id: 100550231
        app-secret: 69b6ab57b22f3c2fe6a6149274e3295e
    browser:
      sign-up-url: /demo-signUp.html
#      signInUrl: /demo-signIn.html


