server:
  context-path: /product

# 单节点配置
spring:
  profiles:
    active: node1
  # 做服务发现是使用（必须唯一）
  application:
    name: jiiiiiin-product
eureka:
  instance:
    hostname: localhost
    # TODO 不生效
#    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    service-url:
      # 指定服务注册中心的地址
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
    # 服务提供方需要注册到eureka-server
    # 如果是需要被zuul调用也需要注册
    register-with-eureka: true
    # 需要获取其他服务提供方，故需要拉取配置信息
    fetch-registry: true

---
# 多节点配置

spring:
  profiles: node1
server:
  port: 7000

---

spring:
  profiles: node2
server:
  port: 7001

